name: MY-CI-DEMO

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Build
        run: |
          yarn install
          yarn build

      - name: Upload
        uses: appleboy/scp-action@master
        with:
          host: 47.98.191.98
          username: root
          password: Aa879757
          source: "build/"
          target: "/root/app"
